### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by gvsurenderreddy** [tolgahanuzun/Remote-Screen-Sharing#1]
Hello sir
can you give me septs how to install it on Linux please.I'm also looking for remote desktop connection like teamviewer but free.VNC was solution but my pc is in nat

apt-get install flask-flask-ngrok
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package flask-flask-ngrok
root@Remotely:~# apt-get install flask-ngrok
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package flask-ngrok
root@Remotely:~# apt-get install pyscreenshot
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package pyscreenshot
root@Remotely:~# apt-get install pillow
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package pillow

**Comment by tolgahanuzun** [comment]
Hello @gvsurenderreddy. This is just for viewing. I'il give you advice. You can use Google Remote Chrome Desktop.

The answer to the question; It is a python package. Not Linux package. 

You have to run it.

```bash
python install -r  requirements.txt
```

**Comment by tolgahanuzun** [comment]
If you want to ask something else, you can create an issue again. I'm guessing the problem is solved. @gvsurenderreddy
